version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - cluster.initial_master_nodes=es01
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elastic
    volumes:
      - /usr/share/elasticsearch/data
  kib01:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kib01
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    depends_on:
      - es01
    expose:
      - 5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
