services:
  # es01:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
  #   container_name: es01
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-docker-cluster
  #     - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
  #     - cluster.initial_master_nodes=es01
  #     - xpack.security.enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - instalite
  #   volumes:
  #     - /usr/share/elasticsearch/data

  # kib01:
  # image: docker.elastic.co/kibana/kibana:8.13.0
  # container_name: kib01
  # environment:
  #   - ELASTICSEARCH_HOSTS=http://es01:9200
  # ports:
  #   - 5601:5601
  # depends_on:
  #   - es01
  # networks:
  #   - instalite

  redis:
    image: redis:7.2.4
    container_name: redis-instalite
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - 6379:6379
    networks:
      - instalite
    volumes:
      - /usr/share/redis/data

  # notifications:
  #   build:
  #     context: .
  #     dockerfile: ./apps/notifications/Dockerfile
  #     target: development
  #   command: npm run start:dev
  #   env_file:
  #     - path: ./apps/notifications/.env
  #   container_name: notifications
  #   depends_on:
  #     - redis

  postgres:
    image: postgres:16.2
    container_name: postgres-instalite
    ports:
      - 5432:5432
    env_file:
      - path: .env
    volumes:
      - /usr/share/postgres/data
    networks:
      - instalite

networks:
  instalite:
    driver: bridge
